"""
Django settings configuration for weather_project.
This file configures core Django functionality + REST Framework customizations:
- Core Django settings (database, auth, static files)
- REST Framework (token auth, pagination, throttling)
- Request logging (structured API request logging)
- Security & performance configurations (debug, allowed hosts)
Generated by Django startproject command and customized for weather API project.
"""

# Standard library imports
import os
from pathlib import Path

# -----------------------------------------------------------------------------
# Core Path Configuration
# -----------------------------------------------------------------------------
# Base directory of the project (parent of settings.py directory)
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# Security Configuration (Development Only)
# WARNING: Update these for production (use environment variables for secret key)
# -----------------------------------------------------------------------------
# Secret key for cryptographic signing (development only - replace in production)
SECRET_KEY = 'test-key-for-development'

# Debug mode (enable only in development; disable in production)
# Shows detailed error pages and enables auto-reload
DEBUG = True

# Allowed hosts (list of host/domain names this Django app can serve)
# Empty list = only localhost/127.0.0.1 in debug mode
ALLOWED_HOSTS = []

# -----------------------------------------------------------------------------
# Installed Applications
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Default Django admin interface
    'django.contrib.admin',
    # Default Django authentication system
    'django.contrib.auth',
    # Default Django content type framework
    'django.contrib.contenttypes',
    # Default Django session management
    'django.contrib.sessions',
    # Default Django message framework
    'django.contrib.messages',
    # Default Django static file management
    'django.contrib.staticfiles',
    
    # Third-party packages
    'rest_framework',                  # Django REST Framework (DRF) core
    'rest_framework.authtoken',        # DRF token authentication support
    'drf_yasg',                        # Swagger/OpenAPI documentation for DRF
    
    # Project-specific applications
    'weather_app',                     # Main weather API application
]

# -----------------------------------------------------------------------------
# Middleware Configuration
# Middleware = processing layers for HTTP requests/responses
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    # Security middleware (HTTPS redirect, XSS protection, etc.)
    'django.middleware.security.SecurityMiddleware',
    # Session management middleware (handles user sessions)
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Common middleware (URL rewriting, content type handling)
    'django.middleware.common.CommonMiddleware',
    # CSRF protection middleware (prevents cross-site request forgery)
    'django.middleware.csrf.CsrfViewMiddleware',
    # Authentication middleware (associates users with requests)
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Message middleware (handles temporary user messages)
    'django.contrib.messages.middleware.MessageMiddleware',
    # Clickjacking protection (X-Frame-Options header)
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -----------------------------------------------------------------------------
# URL Configuration
# -----------------------------------------------------------------------------
# Root URL configuration module for the project
ROOT_URLCONF = 'weather_project.urls'

# -----------------------------------------------------------------------------
# Template Configuration
# -----------------------------------------------------------------------------
TEMPLATES = [
    {
        # Django's default template backend
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Custom template directories (empty = use app-specific templates)
        'DIRS': [],
        # Enable template loading from installed apps
        'APP_DIRS': True,
        'OPTIONS': {
            # Context processors (add variables to all template contexts)
            'context_processors': [
                # Debug context (adds debug flag to templates)
                'django.template.context_processors.debug',
                # Request context (adds request object to templates)
                'django.template.context_processors.request',
                # Authentication context (adds user/auth objects to templates)
                'django.contrib.auth.context_processors.auth',
                # Messages context (adds messages to templates)
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# -----------------------------------------------------------------------------
# WSGI Configuration
# -----------------------------------------------------------------------------
# WSGI application entry point (for production servers like Gunicorn/Nginx)
WSGI_APPLICATION = 'weather_project.wsgi.application'

# -----------------------------------------------------------------------------
# Database Configuration
# -----------------------------------------------------------------------------
# SQLite database (development only; use PostgreSQL/MySQL in production)
DATABASES = {
    'default': {
        # Database engine (SQLite for lightweight development)
        'ENGINE': 'django.db.backends.sqlite3',
        # Database file path (stored in project root as db.sqlite3)
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -----------------------------------------------------------------------------
# Password Validation
# Enforces strong password policies for user accounts
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    # Validate password doesn't match user attributes (e.g., username/email)
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    # Validate password meets minimum length requirement
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # Validate password isn't in common password list
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    # Validate password isn't entirely numeric
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -----------------------------------------------------------------------------
# Internationalization (i18n) Configuration
# -----------------------------------------------------------------------------
# Default language code for the project (English - US)
LANGUAGE_CODE = 'en-us'

# Default time zone (Coordinated Universal Time)
TIME_ZONE = 'UTC'

# Enable internationalization support
USE_I18N = True

# Enable time zone support (datetime handling with time zones)
USE_TZ = True

# -----------------------------------------------------------------------------
# Static Files Configuration
# -----------------------------------------------------------------------------
# URL prefix for static files (CSS, JavaScript, images)
STATIC_URL = 'static/'

# -----------------------------------------------------------------------------
# Default Auto Field
# Sets default primary key field type for all models
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------------------------------------------------------
# Django REST Framework (DRF) Custom Settings
# Core API customization for authentication, permissions, pagination, throttling
# -----------------------------------------------------------------------------
REST_FRAMEWORK = {
    # Authentication Configuration
    # Enable token-based authentication globally for all API endpoints
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    
    # Permission Configuration
    # Require authentication for all API endpoints by default
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Pagination Configuration
    # Use page number pagination (/?page=1) with 5 items per page
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,
    
    # Rate Throttling Configuration
    # Limit API requests to prevent abuse (anon = unauthenticated, user = authenticated)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',    # Throttle for anonymous users
        'rest_framework.throttling.UserRateThrottle',    # Throttle for authenticated users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',  # 10 requests per minute for anonymous users
        'user': '30/minute',  # 30 requests per minute for authenticated users
    }
}

# -----------------------------------------------------------------------------
# Request Logging Configuration
# Structured logging for API requests (fixed: no 'user' field error)
# Logs timestamp, log level, path, HTTP method, and response status to file
# -----------------------------------------------------------------------------
LOGGING = {
    'version': 1,  # Logging configuration version (required by Django)
    'disable_existing_loggers': False,  # Keep default Django loggers active
    'formatters': {
        # Verbose log format with structured fields
        'verbose': {
            'format': '{asctime} {levelname} {path} {method} {status}',
            'style': '{',  # Use brace-style format specifiers
        },
    },
    'handlers': {
        # File handler for writing logs to api_requests.log
        'file': {
            'level': 'INFO',  # Log only INFO level and above
            'class': 'logging.FileHandler',  # Write logs to file
            'filename': 'api_requests.log',  # Log file path (project root)
            'formatter': 'verbose',  # Use verbose formatter defined above
        },
    },
    'loggers': {
        # Log all Django request events
        'django.request': {
            'handlers': ['file'],  # Use file handler for request logs
            'level': 'INFO',       # Log level for request events
            'propagate': True,     # Pass logs to parent loggers
        },
    },
}

# Swagger UI Token Authorization Configuration
SWAGGER_SETTINGS = {
    # Disable default username/password session login
    'USE_SESSION_AUTH': False,
    # Define token authorization method for Swagger
    'SECURITY_DEFINITIONS': {
        'Token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
}
